import { PublicNav, PublicFooter } from "@/components/public-nav";

export const metadata = {
  title: "Terms of Service",
  description: "ProformaFlow terms of service.",
};

export default function TermsPage() {
  return (
    <>
      <PublicNav />
      <main className="flex-grow max-w-3xl mx-auto px-4 py-16">
        <h1 className="font-headline-lg-mobile md:font-headline-lg text-primary mb-8">
          Terms of Service
        </h1>
        <div className="space-y-6 font-body-md text-on-surface-variant">
          <p>Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

          {/* LIMITATION OF LIABILITY & DISCLAIMER - TOP */}
          <section className="border-2 border-secondary bg-secondary-fixed text-on-secondary-fixed p-6 rounded-sm">
            <h2 className="font-headline-sm text-secondary mb-4">LIMITATION OF LIABILITY & DISCLAIMER</h2>
            <div className="font-mono text-xs md:text-sm leading-relaxed space-y-3 text-on-secondary-fixed-variant">
              <p>
                The software is provided <strong>{"as is"}</strong> and <strong>{"as available"}</strong>, without warranties of any kind, whether express, implied, statutory, or otherwise. ProformaFlow makes no warranties, representations, or guarantees regarding the accuracy, completeness, reliability, fitness for a particular purpose, or non-infringement of the software, generated documents, or any output produced.
              </p>
              <p>
                ProformaFlow is a <strong>document formatting and data-mapping automation tool</strong>. It does <strong>not</strong> provide legal advice, customs brokerage services, international trade consulting, or any professional advisory services. The software merely structures user-provided data into standardized document layouts aligned with common carrier and customs formats.
              </p>
              <p>
                <strong>The user is solely and completely responsible</strong> for verifying the accuracy, truthfulness, legal compliance, and regulatory fulfillment of all data entered into the system and all documents generated by the software before presenting them to any customs authority, carrier, or third party in any jurisdiction worldwide.
              </p>
              <p>
                ProformaFlow accepts <strong>zero liability</strong> for any financial losses, cargo holds, detentions, fines, penalties, sanctions, delays, rejections, inspections, seizures, or any other damages—direct, indirect, incidental, consequential, special, or punitive—arising from or related to the use, misuse, or reliance on documents generated by this software. This limitation applies to the fullest extent permitted by applicable law.
              </p>
              <p>
                By using this software, you acknowledge that final customs acceptance and clearance remain entirely at the discretion of the relevant border authorities and carriers. ProformaFlow cannot guarantee, ensure, or certify successful customs entry or regulatory compliance in any country.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-headline-sm text-primary mt-8 mb-3">Service Description</h2>
            <p>
              ProformaFlow is a document formatting tool that helps you generate proforma
              invoices, commercial invoices, and packing lists for international trade. We format
              the data you provide into a professional PDF layout. We do not provide legal,
              customs, or tax advice, and we are not a party to any transaction you document
              using our service.
            </p>
          </section>

          <section>
            <h2 className="font-headline-sm text-primary mt-8 mb-3">No Legal or Customs Guarantee</h2>
            <p>
              Documents generated with ProformaFlow are provided as-is. You are responsible for
              verifying that the content, Incoterms, HS Codes, and declarations comply with the
              regulations of the origin and destination countries and any carrier requirements.
            </p>
          </section>

          <section>
            <h2 className="font-headline-sm text-primary mt-8 mb-3">Subscriptions & Billing</h2>
            <p>
              Paid plans are billed monthly or annually via Stripe. You can cancel or change your
              plan at any time from the Billing page. Cancellations take effect at the end of the
              current billing period.
            </p>
          </section>

          <section>
            <h2 className="font-headline-sm text-primary mt-8 mb-3">Fair Use — Document Limits</h2>
            <p>
              The Starter plan is limited to 3 documents per month with a watermark. Professional
              and Business plans include unlimited document generation subject to reasonable use.
            </p>
          </section>

          <section>
            <h2 className="font-headline-sm text-primary mt-8 mb-3">Data Handling</h2>
            <p>
              See our <a href="/privacy" className="text-primary underline">Privacy Policy</a> for
              full details on what account data we store and what document data we never store.
            </p>
          </section>

          <section>
            <h2 className="font-headline-sm text-primary mt-8 mb-3">Contact</h2>
            <p>Questions about these terms? Contact us at <a href="mailto:soporte@elantimetodo.com" className="text-primary underline">soporte@elantimetodo.com</a>.</p>
          </section>

          {/* LIMITATION OF LIABILITY & DISCLAIMER - BOTTOM */}
          <section className="border-2 border-secondary bg-secondary-fixed text-on-secondary-fixed p-6 rounded-sm mt-12">
            <h2 className="font-headline-sm text-secondary mb-4">LIMITATION OF LIABILITY & DISCLAIMER (REPEATED FOR EMPHASIS)</h2>
            <div className="font-mono text-xs md:text-sm leading-relaxed space-y-3 text-on-secondary-fixed-variant">
              <p>
                ProformaFlow is provided <strong>{"as is"}</strong> without warranties of any kind. ProformaFlow does not provide legal, customs, or trade advisory services. The user bears <strong>sole and absolute responsibility</strong> for all data entered and documents generated.
              </p>
              <p>
                ProformaFlow accepts <strong>no liability whatsoever</strong> for financial loss, cargo detention, fines, penalties, or any damages arising from use of generated documents. Customs clearance is at the sole discretion of border authorities. ProformaFlow cannot guarantee or certify successful customs entry.
              </p>
            </div>
          </section>
        </div>
      </main>
      <PublicFooter />
    </>
  );
}